apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wlnx-api-server
  namespace: default
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
        autoscaling.knative.dev/minScale: "0"
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/memory: "256Mi"
        run.googleapis.com/cpu: "500m"
    spec:
      containerConcurrency: 10
      timeoutSeconds: 300
      containers:
      - name: api-server
        image: gcr.io/PROJECT_ID/wlnx-api-server:latest
        ports:
        - name: http1
          containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: wlnx-secrets
              key: database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: wlnx-secrets
              key: jwt-secret
        - name: API_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: wlnx-secrets
              key: api-secret-key
        - name: TELEGRAM_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: wlnx-secrets
              key: telegram-webhook-secret
        - name: CORS_ORIGIN
          value: "https://wlnx-control-panel-PROJECT_ID.a.run.app"
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
