apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wlnx-control-panel
  namespace: default
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
        autoscaling.knative.dev/minScale: "0"
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/memory: "128Mi"
        run.googleapis.com/cpu: "200m"
    spec:
      containerConcurrency: 10
      timeoutSeconds: 300
      containers:
      - name: control-panel
        image: gcr.io/PROJECT_ID/wlnx-control-panel:latest
        ports:
        - name: http1
          containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: REACT_APP_API_URL
          value: "https://wlnx-api-server-PROJECT_ID.a.run.app/api"
        - name: API_BASE_URL
          value: "https://wlnx-api-server-PROJECT_ID.a.run.app/api"
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
